// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "Nostrdb",
    products: [
        .library(name: "Nostrdb", targets: ["Nostrdb"]),
    ],
    targets: [
        .target(
            name: "Nostrdb",
            path: ".",
            exclude: [
                "test.c",
                "ndb.c",
                "bench-ingest-many.c",
                "testdata",
                "Makefile",
                "CMakeLists.txt",
                "README.md",
                "CHANGELOG.md",
                "LICENSE",
                ".github",
                "devtools",
                "docs",
                "schemas",
                "src/configurator.c",
                "src/giftwrap.c",
                "src/bolt11/bech32_util.c",
                "src/bolt11/node_id.c",
                "deps/secp256k1",
                "deps/libsodium",
                "deps/flatcc/src/compiler",
                "deps/flatcc/src/cli",
                "deps/flatcc/CMakeLists.txt",
                "deps/flatcc/conan",
                "deps/flatcc/doc",
                "deps/flatcc/test",
                "deps/flatcc/samples",
                "deps/flatcc/scripts",
                "deps/flatcc/include/flatcc/portable/pendian.h",
                "deps/flatcc/include/flatcc/portable/pendian_detect.h",
                "deps/lmdb/mdb_copy.c",
                "deps/lmdb/mdb_dump.c",
                "deps/lmdb/mdb_load.c",
                "deps/lmdb/mdb_stat.c",
                "deps/lmdb/mtest.c",
                "deps/lmdb/mtest2.c",
                "deps/lmdb/mtest3.c",
                "deps/lmdb/mtest4.c",
                "deps/lmdb/mtest5.c",
                "deps/lmdb/mtest6.c",
                "ccan/ccan/crypto/sha256/benchmarks",
            ],
            sources: [
                "src/base64.c",
                "src/hmac_sha256.c",
                "src/hkdf_sha256.c",
                "src/nip44.c",
                "src/nostrdb.c",
                "src/invoice.c",
                "src/nostr_bech32.c",
                "src/content_parser.c",
                "src/block.c",
                "src/binmoji.c",
                "src/metadata.c",
                "src/bolt11/bolt11.c",
                "src/bolt11/bech32.c",
                "src/bolt11/amount.c",
                "src/bolt11/hash_u5.c",
                "src/bolt11/error.c",
                "deps/flatcc/src/runtime/json_parser.c",
                "deps/flatcc/src/runtime/verifier.c",
                "deps/flatcc/src/runtime/builder.c",
                "deps/flatcc/src/runtime/emitter.c",
                "deps/flatcc/src/runtime/refmap.c",
                "deps/lmdb/mdb.c",
                "deps/lmdb/midl.c",
                "ccan/ccan/utf8/utf8.c",
                "ccan/ccan/tal/tal.c",
                "ccan/ccan/tal/str/str.c",
                "ccan/ccan/list/list.c",
                "ccan/ccan/mem/mem.c",
                "ccan/ccan/crypto/sha256/sha256.c",
                "ccan/ccan/take/take.c",
            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("src"),
                .headerSearchPath("deps/secp256k1/include"),
                .headerSearchPath("deps/lmdb"),
                .headerSearchPath("deps/flatcc/include"),
                .headerSearchPath("src/bolt11"),
                .headerSearchPath("ccan"),
                .headerSearchPath("deps/libsodium/src/libsodium/include"),
                .define("MDB_SHORT_SEMNAMES", to: "1"),
                .define("MDB_SEM_NAME_PREFIX", to: "\"group.com.damus\""),
                .define("CCAN_TAL_NEVER_RETURN_NULL", to: "1"),
            ]
        ),
    ]
)
